src/Entity/AppReceta.php
<?php
/**
 * Created by PhpStorm.
 * User: ernestosr
 * Date: 11/02/2019
 * Time: 01:01 AM
 */

namespace App\Entity;

use App\Entity\Nomenclador\NcAdd;
use App\Entity\Nomenclador\NcAgudezaVisual;
use App\Entity\Nomenclador\NcDp;
use App\Entity\Nomenclador\NcEje;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class AppReceta
 * @package App\Entity
 *
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class AppReceta extends _BaseEntity_
{
    /**
     * @var DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fecha_refraccion;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppPaciente")
     */
    protected $paciente;

    /**
     * @var string
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    protected $numero;

    /**
     * @var array
     * @ORM\Column(type="json")
     */
    protected $lista_espejuelo;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAdd")
     */
    protected $add;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcDp")
     */
    protected $dp;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppCristal")
     */
    protected $cristal_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcEje")
     */
    protected $eje_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAgudezaVisual")
     */
    protected $a_visual_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppCristal")
     */
    protected $cristal_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcEje")
     */
    protected $eje_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAgudezaVisual")
     */
    protected $a_visual_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityUser")
     * @ORM\JoinColumn(name="usuario_creador_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario_creador;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityOffice")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    protected $office_creacion;

    /**
     * @var
     * @ORM\OneToOne(targetEntity="App\Entity\AppOrdenServicio", mappedBy="receta")
     */
    protected $orden_servicio;

    public function __construct()
    {
        $this->fecha_refraccion = new DateTime('now');
        $this->lista_espejuelo = array();
    }

    public function __toString()
    {
        return (string)$this->numero;
    }

    public function getNumero(): ?string
    {
        return (string)$this->numero;
    }

    public function setNumero(?string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getCristalOd(): ?AppCristal
    {
        return $this->cristal_od;
    }

    public function setCristalOd(?AppCristal $cristal_od): self
    {
        $this->cristal_od = $cristal_od;

        return $this;
    }

    public function getCristalOi(): ?AppCristal
    {
        return $this->cristal_oi;
    }

    public function setCristalOi(?AppCristal $cristal_oi): self
    {
        $this->cristal_oi = $cristal_oi;

        return $this;
    }

    public function getAdd(): ?NcAdd
    {
        return $this->add;
    }

    public function setAdd(?NcAdd $add): self
    {
        $this->add = $add;

        return $this;
    }

    public function getDp(): ?NcDp
    {
        return $this->dp;
    }

    public function setDp(?NcDp $dp): self
    {
        $this->dp = $dp;

        return $this;
    }

    public function getEjeOd(): ?NcEje
    {
        return $this->eje_od;
    }

    public function setEjeOd(?NcEje $eje_od): self
    {
        $this->eje_od = $eje_od;

        return $this;
    }

    public function getAVisualOd(): ?NcAgudezaVisual
    {
        return $this->a_visual_od;
    }

    public function setAVisualOd(?NcAgudezaVisual $a_visual_od): self
    {
        $this->a_visual_od = $a_visual_od;

        return $this;
    }

    public function getEjeOi(): ?NcEje
    {
        return $this->eje_oi;
    }

    public function setEjeOi(?NcEje $eje_oi): self
    {
        $this->eje_oi = $eje_oi;

        return $this;
    }

    public function getAVisualOi(): ?NcAgudezaVisual
    {
        return $this->a_visual_oi;
    }

    public function setAVisualOi(?NcAgudezaVisual $a_visual_oi): self
    {
        $this->a_visual_oi = $a_visual_oi;

        return $this;
    }

    public function getFechaRefraccion(): ?\DateTimeInterface
    {
        return $this->fecha_refraccion;
    }

    public function setFechaRefraccion(?\DateTimeInterface $fecha_refraccion): self
    {
        $this->fecha_refraccion = $fecha_refraccion;

        return $this;
    }

    public function getUsuarioCreador(): ?SecurityUser
    {
        return $this->usuario_creador;
    }

    public function setUsuarioCreador(?SecurityUser $usuario_creador): self
    {
        $this->usuario_creador = $usuario_creador;

        return $this;
    }

    public function getOfficeCreacion(): ?SecurityOffice
    {
        return $this->office_creacion;
    }

    public function setOfficeCreacion(?SecurityOffice $office_creacion): self
    {
        $this->office_creacion = $office_creacion;

        return $this;
    }

    public function getPaciente(): ?AppPaciente
    {
        return $this->paciente;
    }

    public function setPaciente(?AppPaciente $paciente): self
    {
        $this->paciente = $paciente;

        return $this;
    }

    public function getListaEspejuelo()
    {
        return $this->lista_espejuelo;
    }

    public function setListaEspejuelo($lista_espejuelo): self
    {
        $this->lista_espejuelo = $lista_espejuelo;

        return $this;
    }

    public function getOrdenServicio(): ?AppOrdenServicio
    {
        return $this->orden_servicio;
    }

    public function setOrdenServicio(?AppOrdenServicio $orden_servicio): self
    {
        $this->orden_servicio = $orden_servicio;

        // set (or unset) the owning side of the relation if necessary
        $newReceta = $orden_servicio === null ? null : $this;
        if ($newReceta !== $orden_servicio->getReceta()) {
            $orden_servicio->setReceta($newReceta);
        }

        return $this;
    }
}

src/Entity/MovimientoAlmacen/InformeRecepcionOptica.php
<?php


namespace App\Entity\MovimientoAlmacen;

use App\Entity\SecurityOffice;
use App\Entity\SecurityUser;
use App\Entity\_BaseEntity_;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InformeRecepcionOpticaRepository")
 */
class InformeRecepcionOptica extends _BaseEntity_
{
    /**
     * @var DateTime
     *
     * @ORM\Column(name="fecha", type="date")
     */
    protected $fecha;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $numero_factura;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $numero_informe_recepcion;

    /**
     * @var string
     * @ORM\Column(type="json_array", nullable=true)
     */
    protected $dato_extra;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityUser")
     * @ORM\JoinColumn(name="usuario_creador_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario_creador;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityUser")
     * @ORM\JoinColumn(name="usuario_confirmado_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario_confirmado;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityUser")
     * @ORM\JoinColumn(name="usuario_economico_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario_economico;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityOffice")
     * @ORM\JoinColumn(name="office_origen_id", referencedColumnName="id", nullable=true)
     */
    protected $office_origen;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityOffice")
     * @ORM\JoinColumn(name="office_destino_id", referencedColumnName="id")
     */
    protected $office_destino;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    protected $confirmado;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    protected $pendiente;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    protected $devuelto;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $devuelto_descripcion;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MovimientoAlmacen\InformeRecepcionOpticaAccesorio", mappedBy="informe_recepcion", cascade={"all"}, orphanRemoval=true)
     */
    protected $accesorios;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MovimientoAlmacen\InformeRecepcionOpticaArmadura", mappedBy="informe_recepcion", cascade={"all"}, orphanRemoval=true)
     */
    public $armaduras;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MovimientoAlmacen\InformeRecepcionOpticaCristal", mappedBy="informe_recepcion", cascade={"all"}, orphanRemoval=true)
     */
    protected $cristales;

    /**
     * @ORM\OneToMany(targetEntity="InformeRecepcionOpticaLupa", mappedBy="informe_recepcion", cascade={"all"}, orphanRemoval=true)
     */
    protected $lupas;

    /**
     * @ORM\OneToMany(targetEntity="InformeRecepcionOpticaTinteCrital", mappedBy="informe_recepcion", cascade={"all"}, orphanRemoval=true)
     */
    protected $tinte_cristales;

    public $tipo_factura;

    public function __toString()
    {
        return (string)$this->getId();
    }


    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->fecha = new DateTime();
        $this->devuelto = false;
        $this->pendiente = false;
        $this->confirmado = false;
        $this->accesorios = new ArrayCollection();
        $this->armaduras = new ArrayCollection();
        $this->cristales = new ArrayCollection();
        $this->lupas = new ArrayCollection();
        $this->tinte_cristales = new ArrayCollection();
        $this->dato_extra = new ArrayCollection();
    }

    public function getFecha(): ?DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getNumeroFactura(): ?string
    {
        return $this->numero_factura;
    }

    public function setNumeroFactura(string $numero_factura): self
    {
        $this->numero_factura = $numero_factura;

        return $this;
    }

    public function getDevuelto(): ?bool
    {
        return $this->devuelto;
    }

    public function setDevuelto(bool $devuelto): self
    {
        $this->devuelto = $devuelto;

        return $this;
    }

    public function getDevueltoDescripcion(): ?string
    {
        return $this->devuelto_descripcion;
    }

    public function setDevueltoDescripcion(?string $devuelto_descripcion): self
    {
        $this->devuelto_descripcion = $devuelto_descripcion;

        return $this;
    }

    public function getConfirmado(): ?bool
    {
        return $this->confirmado;
    }

    public function setConfirmado(bool $confirmado): self
    {
        $this->confirmado = $confirmado;

        return $this;
    }
//
//    public function getOfficeOrigen(): ?SecurityOffice
//    {
//        return $this->office_origen;
//    }
//
//    public function setOfficeOrigen(?SecurityOffice $office_origen): self
//    {
//        $this->office_origen = $office_origen;
//
//        return $this;
//    }

    public function getOfficeDestino(): ?SecurityOffice
    {
        return $this->office_destino;
    }

    public function setOfficeDestino(?SecurityOffice $office_destino): self
    {
        $this->office_destino = $office_destino;

        return $this;
    }

    /**
     * @return Collection|InformeRecepcionOpticaAccesorio[]
     */
    public function getAccesorios(): Collection
    {
        return $this->accesorios;
    }

    public function addAccesorio(InformeRecepcionOpticaAccesorio $accesorio): self
    {
        if (!$this->accesorios->contains($accesorio)) {
            $this->accesorios[] = $accesorio;
            $accesorio->setInformeRecepcion($this);
        }

        return $this;
    }

    public function removeAccesorio(InformeRecepcionOpticaAccesorio $accesorio): self
    {
        if ($this->accesorios->contains($accesorio)) {
            $this->accesorios->removeElement($accesorio);
            // set the owning side to null (unless already changed)
            if ($accesorio->getInformeRecepcion() === $this) {
                $accesorio->setInformeRecepcion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|InformeRecepcionOpticaArmadura[]
     */
    public function getArmaduras(): Collection
    {
        return $this->armaduras;
    }

    public function addArmadura(InformeRecepcionOpticaArmadura $armadura): self
    {
        if (!$this->armaduras->contains($armadura)) {
            $this->armaduras[] = $armadura;
            $armadura->setInformeRecepcion($this);
        }

        return $this;
    }

    public function removeArmadura(InformeRecepcionOpticaArmadura $armadura): self
    {
        if ($this->armaduras->contains($armadura)) {
            $this->armaduras->removeElement($armadura);
            // set the owning side to null (unless already changed)
            if ($armadura->getInformeRecepcion() === $this) {
                $armadura->setInformeRecepcion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|InformeRecepcionOpticaCristal[]
     */
    public function getCristales(): Collection
    {
        return $this->cristales;
    }

    public function addCristale(InformeRecepcionOpticaCristal $cristale): self
    {
        if (!$this->cristales->contains($cristale)) {
            $this->cristales[] = $cristale;
            $cristale->setInformeRecepcion($this);
        }

        return $this;
    }

    public function removeCristale(InformeRecepcionOpticaCristal $cristale): self
    {
        if ($this->cristales->contains($cristale)) {
            $this->cristales->removeElement($cristale);
            // set the owning side to null (unless already changed)
            if ($cristale->getInformeRecepcion() === $this) {
                $cristale->setInformeRecepcion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|InformeRecepcionOpticaLupa[]
     */
    public function getLupas(): Collection
    {
        return $this->lupas;
    }

    public function addLupa(InformeRecepcionOpticaLupa $lupa): self
    {
        if (!$this->lupas->contains($lupa)) {
            $this->lupas[] = $lupa;
            $lupa->setInformeRecepcion($this);
        }

        return $this;
    }

    public function removeLupa(InformeRecepcionOpticaLupa $lupa): self
    {
        if ($this->lupas->contains($lupa)) {
            $this->lupas->removeElement($lupa);
            // set the owning side to null (unless already changed)
            if ($lupa->getInformeRecepcion() === $this) {
                $lupa->setInformeRecepcion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|InformeRecepcionOpticaTinteCrital[]
     */
    public function getTinteCristales(): Collection
    {
        return $this->tinte_cristales;
    }

    public function addTinteCristale(InformeRecepcionOpticaTinteCrital $tinteCristale): self
    {
        if (!$this->tinte_cristales->contains($tinteCristale)) {
            $this->tinte_cristales[] = $tinteCristale;
            $tinteCristale->setInformeRecepcion($this);
        }

        return $this;
    }

    public function removeTinteCristale(InformeRecepcionOpticaTinteCrital $tinteCristale): self
    {
        if ($this->tinte_cristales->contains($tinteCristale)) {
            $this->tinte_cristales->removeElement($tinteCristale);
            // set the owning side to null (unless already changed)

src/Resources/views/Admin/informe_recepcion_optica/modelo/informe_recepcion.html.twig
{% extends "base-print-layout.html.twig" %}
{% block title %}Factura para {{ object.officeDestino }}{% endblock %}
{% block body %}
    {#  @var \App\Entity\MovimientoAlmacen\InformeRecepcionOptica object   #}
    <table>
        <thead>
        <tr>
            <th style="width: 30%">ENTIDAD: {{ object.officeDestino }}</th>
            <th style="width: 30%">CÓDIGO: {{ object.officeDestino.number }}</th>
            <th rowspan="2" style="width: 40%"><h3>Informe de Recepción #{{ object.numeroInformeRecepcion }}</h3></th>
        </tr>
        <tr>
            <th>ALMACÉN: {{ tipo_factura }}</th>
            <th>FECHA: {{ object.createdAt|date('Y-m-d') }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="3" style="padding: 0px">
                {% include '::Admin/informe_recepcion_optica/modelo/list_producto_saldo.html.twig' %}
            </td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3" style="padding: 0px">
                <table>
                    <tbody>
                    <tr>
                        <th colspan="2">Recibido por:</th>
                        <th colspan="2">Autorizado por:</th>
                    </tr>
                    <tr>
                        <td style="width: 35%">Nombre y Apellidos: {#<strong>{{ object.usuarioConfirmado }}</strong>#}</td>
                        <td style="width: 15%">Firma:</td>
                        <td style="width: 35%">Nombre y Apellidos: <strong>{{ object.usuarioEconomico }}</strong></td>
                        <td style="width: 15%">Firma:</td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

src/Resources/views/Admin/informe_recepcion_optica/modelo/list_producto.html.twig
{#  @var \App\Entity\MovimientoAlmacen\InformeRecepcionOptica object   #}
<table>
    <thead>
    <tr>
        <th>CÓDIGO</th>
        <th>DESCRIPCIÓN</th>
        <th>CANTIDAD</th>
        <th>PRECIO DE COSTO</th>
        <th>PRECIO DE VENTA</th>
        <th>IMPORTE DE COSTO</th>
        <th>IMPORTE DE VENTA</th>
    </tr>
    </thead>
    <tbody>
    {% set productos = [
        object.accesorios,
        object.armaduras,
        object.cristales,
        object.tinteCristales,
        object.lupas,
    ] %}

    {% set importe_total_costo = 0 %}
    {% set importe_total_venta = 0 %}
    {% for producto in productos %}
        {% for value in producto %}
            {% include '::Admin/Almacen/_producto_tr_pdf.html.twig' %}
            {% set importe_total_costo = importe_total_costo + (value.cantidad * value.producto.producto.precioCosto) %}
            {% set importe_total_venta = importe_total_venta + (value.cantidad * value.producto.producto.precio) %}
        {% endfor %}
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <th colspan="5" style="text-align: right">Total:</th>
        <th style="text-align: right">$ {{ importe_total_costo|number_format(2, '.', ',') }}</th>
        <th style="text-align: right">$ {{ importe_total_venta|number_format(2, '.', ',') }}</th>
    </tr>
    </tfoot>
</table>

src/Resources/views/Admin/informe_recepcion_optica/modelo/list_producto_saldo.html.twig
{#  @var \App\Entity\MovimientoAlmacen\InformeRecepcionOptica object   #}
<table>
    <thead>
    <tr>
        <th>CÓDIGO</th>
        <th>DESCRIPCIÓN</th>
        <th>CANTIDAD</th>
        <th>PRECIO DE COSTO</th>
        <th>PRECIO DE VENTA</th>
        <th>IMPORTE DE COSTO</th>
        <th>IMPORTE DE VENTA</th>
        <th>SALDO</th>
    </tr>
    </thead>
    <tbody>
    {% set productos = [
        object.accesorios,
        object.armaduras,
        object.cristales,
        object.tinteCristales,
        object.lupas,
    ] %}

    {% set importe_total_costo = 0 %}
    {% set importe_total_venta = 0 %}
    {% for producto in productos %}
        {% for value in producto %}
            {% include '::Admin/Almacen/_producto_tr_pdf_saldo.html.twig' %}
            {% set importe_total_costo = importe_total_costo + (value.cantidad * value.producto.producto.precioCosto) %}
            {% set importe_total_venta = importe_total_venta + (value.cantidad * value.producto.producto.precio) %}
        {% endfor %}
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <th colspan="5" style="text-align: right">Total:</th>
        <th style="text-align: right">$ {{ importe_total_costo|number_format(2, '.', ',') }}</th>
        <th style="text-align: right">$ {{ importe_total_venta|number_format(2, '.', ',') }}</th>
        <th></th>
    </tr>
    </tfoot>
</table>

src/Resources/views/Admin/informe_recepcion_optica/modelo/vale_salida.html.twig
{% extends "base-print-layout.html.twig" %}
{% block title %}Factura para {{ object.officeDestino }}{% endblock %}
{% block body %}
    {#  @var \App\Entity\MovimientoAlmacen\InformeRecepcionOptica object   #}
    <table>
        <thead>
        <tr>
            <th style="width: 30%">ENTIDAD: {{ object.officeDestino }}</th>
            <th style="width: 30%">CÓDIGO: {{ object.officeDestino.number }}</th>
            <th rowspan="2" style="width: 40%"><h3>FACTURA #{{ object.numeroFactura }}</h3></th>
        </tr>
        <tr>
            <th>ALMACÉN: {{ tipo_factura }}</th>
            <th>FECHA: {{ object.createdAt|date('Y-m-d') }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="3" style="padding: 0px">
                {% include '::Admin/informe_recepcion_optica/modelo/list_producto.html.twig' %}
            </td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3" style="padding: 0px">
                <table>
                    <tbody>
                    <tr>
                        <th colspan="2">Recibido por:</th>
                        <th colspan="2">Despachado por:</th>
                    </tr>
                    <tr>
                        <td style="width: 35%">Nombre y Apellidos: <strong>{{ object.usuarioConfirmado }}</strong></td>
                        <td style="width: 15%">Firma:</td>
                        <td style="width: 35%">Nombre y Apellidos: <strong>{{ object.usuarioCreador }}</strong></td>
                        <td style="width: 15%">Firma:</td>
                    </tr>
                    <tr>
                        <th colspan="2">Transportado por:</th>
                        <th colspan="2">Autorizado por:</th>
                    </tr>
                    <tr>
                        <td style="width: 35%">Nombre y Apellidos:</td>
                        <td style="width: 15%">Firma:</td>
                        <td style="width: 35%">Nombre y Apellidos:</td>
                        <td style="width: 15%">Firma:</td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tfoot>
    </table>
{% endblock %}