src/Auditoria/Entity/Association.php
<?php
/**
 * Created by PhpStorm.
 * User: Carlos
 * Date: 24/02/2017
 * Time: 04:03 PM
 */

namespace  App\Auditoria\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="auditoria_association")
 */
class Association
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @ORM\Column(length=128)
     */
    private $typ;
    /**
     * @ORM\Column(length=128)
     */
    private $tbl;
    /**
     * @ORM\Column(nullable=true)
     */
    private $label;
    /**
     * @ORM\Column
     */
    private $fk;
    /**
     * @ORM\Column
     */
    private $class;
    public function getId()
    {
        return $this->id;
    }
    public function getTyp()
    {
        return $this->typ;
    }
    public function getTypLabel()
    {
        $words = explode('.', $this->getTyp());
        return implode(' ', array_map('ucfirst', explode('_', end($words))));
    }
    public function getTbl()
    {
        return $this->tbl;
    }
    public function getLabel()
    {
        return $this->label;
    }
    public function getFk()
    {
        return $this->fk;
    }
    public function getClass()
    {
        return $this->class;
    }

    public function setTyp(string $typ): self
    {
        $this->typ = $typ;

        return $this;
    }

    public function setTbl(string $tbl): self
    {
        $this->tbl = $tbl;

        return $this;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function setFk(string $fk): self
    {
        $this->fk = $fk;

        return $this;
    }

    public function setClass(string $class): self
    {
        $this->class = $class;

        return $this;
    }
}

src/Auditoria/Entity/AuditoriaLog.php
<?php
namespace  App\Auditoria\Entity;
/**
 * Created by PhpStorm.
 * User: Carlos
 * Date: 24/02/2017
 * Time: 04:00 PM
 */


use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="auditoria_log")
 */

class AuditoriaLog
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @ORM\Column(length=12)
     */
    private $action;
    /**
     * @ORM\Column(length=128)
     */
    private $tbl;

    /**
     * @ORM\Column(length=128)
     */
    private $ip;

    /**
     * @ORM\OneToOne(targetEntity="App\Auditoria\Entity\Association")
     * @ORM\JoinColumn(nullable=false)
     */
    private $source;
    /**
     * @ORM\OneToOne(targetEntity="App\Auditoria\Entity\Association")
     */
    private $target;
    /**
     * @ORM\OneToOne(targetEntity="App\Auditoria\Entity\Association")
     */
    private $blame;

    /**
     * @ORM\OneToOne(targetEntity="App\Auditoria\Entity\Association")
     */
    private $blame_impersonate;

    
    /**
     *
     */
    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $diff;
    /**
     * @ORM\Column(type="datetime")
     */
    private $loggedAt;
    public function getId()
    {
        return $this->id;
    }
    public function getAction()
    {
        return $this->action;
    }
    public function getTbl()
    {
        return $this->tbl;
    }
    public function getSource()
    {
        return $this->source;
    }
    public function getTarget()
    {
        return $this->target;
    }
    public function getBlame()
    {
        return $this->blame;
    }
    public function getDiff()
    {
        return $this->diff;
    }
    public function getLoggedAt()
    {
        return $this->loggedAt;
    }

    public function __toString()
    {
        $label = ($this->getSource()->getLabel()) ? " : ".$this->getSource()->getLabel() : "";
        return $this->getSource()->getTypLabel()." ".$label;
    }

    /**
     * Set action
     *
     * @param string $action
     *
     * @return AuditoriaLog
     */
    public function setAction($action)
    {
        $this->action = $action;

        return $this;
    }

    /**
     * Set tbl
     *
     * @param string $tbl
     *
     * @return AuditoriaLog
     */
    public function setTbl($tbl)
    {
        $this->tbl = $tbl;

        return $this;
    }

    /**
     * Set ip
     *
     * @param string $ip
     *
     * @return AuditoriaLog
     */
    public function setIp($ip)
    {
        $this->ip = $ip;

        return $this;
    }

    /**
     * Get ip
     *
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Set diff
     *
     * @param array $diff
     *
     * @return AuditoriaLog
     */
    public function setDiff($diff)
    {
        $this->diff = $diff;

        return $this;
    }

    /**
     * Set loggedAt
     *
     * @param \DateTime $loggedAt
     *
     * @return AuditoriaLog
     */
    public function setLoggedAt($loggedAt)
    {
        $this->loggedAt = $loggedAt;

        return $this;
    }

    /**
     * Set source
     *
     * @param \App\Auditoria\Entity\Association $source
     *
     * @return AuditoriaLog
     */
    public function setSource(\App\Auditoria\Entity\Association $source)
    {
        $this->source = $source;

        return $this;
    }

    /**
     * Set target
     *
     * @param \App\Auditoria\Entity\Association $target
     *
     * @return AuditoriaLog
     */
    public function setTarget(\App\Auditoria\Entity\Association $target = null)
    {
        $this->target = $target;

        return $this;
    }

    /**
     * Set blame
     *
     * @param \App\Auditoria\Entity\Association $blame
     *
     * @return AuditoriaLog
     */
    public function setBlame(\App\Auditoria\Entity\Association $blame = null)
    {
        $this->blame = $blame;

        return $this;
    }

    /**
     * Set blameImpersonate
     *
     * @param \App\Auditoria\Entity\Association $blameImpersonate
     *
     * @return AuditoriaLog
     */
    public function setBlameImpersonate(\App\Auditoria\Entity\Association $blameImpersonate = null)
    {
        $this->blame_impersonate = $blameImpersonate;

        return $this;
    }

    /**
     * Get blameImpersonate
     *
     * @return \App\Auditoria\Entity\Association
     */
    public function getBlameImpersonate()
    {
        return $this->blame_impersonate;
    }
}

templates/app/auditoria/assoc.html.twig
{#<a href="{{ path('admin_sip_auditoria_auditorialog_list', {filters: {history: assoc.fk, source_class: assoc.class}}) }}">#}
<a href="{{ path('admin_app_auditoria_auditorialog_list', {'filter[source_class][value]': assoc.class}) }}">
    {{ assoc.label }} <i class="fa fa-history" title="Mostrar todo el histórico"></i>
</a>

templates/app/auditoria/associate.html.twig
<tr>
    <td class="col-min">
        <span class="label label-success"><i class="fa fa-random"></i></span>
    </td>
    <td>
        <strong>{{ log.source.typLabel }}</strong> {{ audit_assoc(log.source) }} fue asociado con

        <strong>{{ log.target.typLabel }}</strong> {{ audit_assoc(log.target) }},

    </td>
    <td class="col-min">{{ log.loggedAt| date("d/m/y") }}</td>
    <td class="col-min"></td>
</tr>

templates/app/auditoria/blame.html.twig
{% if blame %}
    por {{ audit_assoc(blame) }}
{% else %}
    por <strong>super usuario o cron.</strong>
{% endif %}

templates/app/auditoria/diff.html.twig
{% extends base_template %}

{% block show %}
    {%  set log = object %}

        <h1><small>Diferencias en Auditoría</small></h1>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-archive"></i> {{ audit_assoc(log.source) }}</h3>
            </div>

            {% if log.action == 'insert' %}
                <ul class="list-group">
                    {% for field, change in log.diff %}
                        <li class="list-group-item">
                            <span class="badge">{{ audit_value(change.new) }}</span>
                            {{ field }}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <table class="table table-striped">
                    <tr>
                        <th>Propiedad</th>
                        <th>Viejo</th>
                        <th>Nuevo</th>
                    </tr>
                    {% for field, change in log.diff %}
                        <tr>
                            <td>{{ field }}</td>
                            <td>{{ audit_value(change.old) }}</td>
                            <td>{{ audit_value(change.new) }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

        </div>
{% endblock %}

templates/app/auditoria/dissociate.html.twig
<tr>
    <td class="col-min">
        <span class="label label-warning"><i class="fa fa-random"></i></span>
    </td>
    <td>
        <strong>{{ log.source.typLabel }}</strong> {{ audit_assoc(log.source) }} fue desasociado
        <strong>{{ log.target.typLabel }}</strong> {{ audit_assoc(log.target) }},
        {{ audit_blame(log.blame) }}  desde {{ log.ip }}
        {% if log.blameImpersonate is defined and log.blameImpersonate  is not null %}
            suplantado por  {{ audit_assoc(log.blameImpersonate) }}
        {% endif %}
    </td>
    <td class="col-min">{{ log.loggedAt | date("d/m/y") }}</td>
    <td class="col-min"></td>
</tr>

templates/app/auditoria/insert.html.twig
<tr>
    <td class="col-min">
        <span class="label label-success"><i class="fa fa-plus"></i></span>
    </td>
    <td>
        Nuevo <strong>{{ log.source.typLabel }}</strong> {{ audit_assoc(log.source) }} fue insertado,
        {{ audit_blame(log.blame) }}  desde {{ log.ip }}
        {% if log.blameImpersonate is defined and log.blameImpersonate  is not null %}
            suplantado por  {{ audit_assoc(log.blameImpersonate) }}
        {% endif %}
    </td>
    <td class="col-min"> {{ log.loggedAt | date("d/m/Y") }}</td>
    <td class="col-min">
        <a class="btn btn-xs btn-link" href="{{ path('admin_app_auditoria_auditorialog_show', {id: log.id}) }}">
            <i class="fa fa-search" title="Mostrar Diferencias"></i>
        </a>
    </td>
</tr>

templates/app/auditoria/remove.html.twig
<tr>
    <td class="col-min">
        <span class="label label-danger"><i class="fa fa-times"></i></span>
    </td>
    <td>
        <strong>{{ log.source.typLabel }}</strong> {{ audit_assoc(log.source) }} fue eliminado
        {{ audit_blame(log.blame) }}  desde {{ log.ip }}
        {% if log.blameImpersonate is defined and log.blameImpersonate  is not null %}
            suplantado por  {{ audit_assoc(log.blameImpersonate) }}
        {% endif %}
    </td>
    <td class="col-min">{{ log.loggedAt | date("d/m/y") }}</td>
    <td class="col-min">
    </td>
</tr>

templates/app/auditoria/update.html.twig
<tr>
    <td class="col-min">
        <span class="label label-info"><i class="fa fa-pencil"></i></span>
    </td>
    <td>
        <strong>{{ log.source.typLabel }}</strong> {{ audit_assoc(log.source) }} fue actualizado
        {{ audit_blame(log.blame) }} desde {{ log.ip }}
        {% if log.blameImpersonate is defined and log.blameImpersonate  is not null %}
            suplantado por  {{ audit_assoc(log.blameImpersonate) }}
        {% endif %}
    </td>
    <td class="col-min">{{ log.loggedAt | date("d/m/y") }}</td>
    <td class="col-min">
        <a class="btn btn-xs btn-link" href="{{ path('admin_app_auditoria_auditorialog_show', {id: log.id}) }}">
            <i class="fa fa-search" title="Mostrar Diferencias"></i>
        </a>
    </td>
</tr>