src/Entity/AppReceta.php
<?php
/**
 * Created by PhpStorm.
 * User: ernestosr
 * Date: 11/02/2019
 * Time: 01:01 AM
 */

namespace App\Entity;

use App\Entity\Nomenclador\NcAdd;
use App\Entity\Nomenclador\NcAgudezaVisual;
use App\Entity\Nomenclador\NcDp;
use App\Entity\Nomenclador\NcEje;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class AppReceta
 * @package App\Entity
 *
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class AppReceta extends _BaseEntity_
{
    /**
     * @var DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fecha_refraccion;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppPaciente")
     */
    protected $paciente;

    /**
     * @var string
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    protected $numero;

    /**
     * @var array
     * @ORM\Column(type="json")
     */
    protected $lista_espejuelo;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAdd")
     */
    protected $add;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcDp")
     */
    protected $dp;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppCristal")
     */
    protected $cristal_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcEje")
     */
    protected $eje_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAgudezaVisual")
     */
    protected $a_visual_od;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppCristal")
     */
    protected $cristal_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcEje")
     */
    protected $eje_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nomenclador\NcAgudezaVisual")
     */
    protected $a_visual_oi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityUser")
     * @ORM\JoinColumn(name="usuario_creador_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario_creador;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecurityOffice")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    protected $office_creacion;

    /**
     * @var
     * @ORM\OneToOne(targetEntity="App\Entity\AppOrdenServicio", mappedBy="receta")
     */
    protected $orden_servicio;

    public function __construct()
    {
        $this->fecha_refraccion = new DateTime('now');
        $this->lista_espejuelo = array();
    }

    public function __toString()
    {
        return (string)$this->numero;
    }

    public function getNumero(): ?string
    {
        return (string)$this->numero;
    }

    public function setNumero(?string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getCristalOd(): ?AppCristal
    {
        return $this->cristal_od;
    }

    public function setCristalOd(?AppCristal $cristal_od): self
    {
        $this->cristal_od = $cristal_od;

        return $this;
    }

    public function getCristalOi(): ?AppCristal
    {
        return $this->cristal_oi;
    }

    public function setCristalOi(?AppCristal $cristal_oi): self
    {
        $this->cristal_oi = $cristal_oi;

        return $this;
    }

    public function getAdd(): ?NcAdd
    {
        return $this->add;
    }

    public function setAdd(?NcAdd $add): self
    {
        $this->add = $add;

        return $this;
    }

    public function getDp(): ?NcDp
    {
        return $this->dp;
    }

    public function setDp(?NcDp $dp): self
    {
        $this->dp = $dp;

        return $this;
    }

    public function getEjeOd(): ?NcEje
    {
        return $this->eje_od;
    }

    public function setEjeOd(?NcEje $eje_od): self
    {
        $this->eje_od = $eje_od;

        return $this;
    }

    public function getAVisualOd(): ?NcAgudezaVisual
    {
        return $this->a_visual_od;
    }

    public function setAVisualOd(?NcAgudezaVisual $a_visual_od): self
    {
        $this->a_visual_od = $a_visual_od;

        return $this;
    }

    public function getEjeOi(): ?NcEje
    {
        return $this->eje_oi;
    }

    public function setEjeOi(?NcEje $eje_oi): self
    {
        $this->eje_oi = $eje_oi;

        return $this;
    }

    public function getAVisualOi(): ?NcAgudezaVisual
    {
        return $this->a_visual_oi;
    }

    public function setAVisualOi(?NcAgudezaVisual $a_visual_oi): self
    {
        $this->a_visual_oi = $a_visual_oi;

        return $this;
    }

    public function getFechaRefraccion(): ?\DateTimeInterface
    {
        return $this->fecha_refraccion;
    }

    public function setFechaRefraccion(?\DateTimeInterface $fecha_refraccion): self
    {
        $this->fecha_refraccion = $fecha_refraccion;

        return $this;
    }

    public function getUsuarioCreador(): ?SecurityUser
    {
        return $this->usuario_creador;
    }

    public function setUsuarioCreador(?SecurityUser $usuario_creador): self
    {
        $this->usuario_creador = $usuario_creador;

        return $this;
    }

    public function getOfficeCreacion(): ?SecurityOffice
    {
        return $this->office_creacion;
    }

    public function setOfficeCreacion(?SecurityOffice $office_creacion): self
    {
        $this->office_creacion = $office_creacion;

        return $this;
    }

    public function getPaciente(): ?AppPaciente
    {
        return $this->paciente;
    }

    public function setPaciente(?AppPaciente $paciente): self
    {
        $this->paciente = $paciente;

        return $this;
    }

    public function getListaEspejuelo()
    {
        return $this->lista_espejuelo;
    }

    public function setListaEspejuelo($lista_espejuelo): self
    {
        $this->lista_espejuelo = $lista_espejuelo;

        return $this;
    }

    public function getOrdenServicio(): ?AppOrdenServicio
    {
        return $this->orden_servicio;
    }

    public function setOrdenServicio(?AppOrdenServicio $orden_servicio): self
    {
        $this->orden_servicio = $orden_servicio;

        // set (or unset) the owning side of the relation if necessary
        $newReceta = $orden_servicio === null ? null : $this;
        if ($newReceta !== $orden_servicio->getReceta()) {
            $orden_servicio->setReceta($newReceta);
        }

        return $this;
    }
}

src/Resources/views/Admin/receta/buttons__others.html.twig
{# @var object \App\Entity\AppReceta #}
{% if object.ordenServicio is null %}
    <a href="{{ path('admin_app_appordenservicio_create',{"receta":object.id}) }}"
       class="btn btn-sm btn-success view_link" title="Crear receta">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        Crear Orden
    </a>
{% else %}
    <a href="#" onclick="alert('En desarrollo')"
       class="btn btn-sm btn-default view_link" title="Crear receta">
        <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        Ver Orden
    </a>
{% endif %}

src/Resources/views/Admin/receta/create_receta_paciente.html.twig
{% extends base_template %}
{% use '@SonataAdmin/CRUD/base_edit_form.html.twig' with form as parentForm %}

{% block form %}
    {% import "@SonataAdmin/CRUD/base_edit_form_macro.html.twig" as form_helper %}
    {{ sonata_block_render_event('sonata.admin.edit.form.top', { 'admin': admin, 'object': object }) }}

    {# NEXT_MAJOR: remove default filter #}
    {% set url = 'crear_receta_paciente' %}

    {% if not admin.hasRoute(url) %}
        <div>
            {{ "form_not_available"|trans({}, "SonataAdminBundle") }}
        </div>
    {% else %}
        <form
                {% if sonata_admin.adminPool.getOption('form_type') == 'horizontal' %}class="form-horizontal"{% endif %}
                role="form"
                {# NEXT_MAJOR: remove default filter #}
                action="{% block sonata_form_action_url %}{{ admin.generateUrl(url, {'id': id}) }}{% endblock %}"
                {% if form.vars.multipart %} enctype="multipart/form-data"{% endif %}
                method="POST"
                {% if not sonata_admin.adminPool.getOption('html5_validate') %}novalidate="novalidate"{% endif %}
                {% block sonata_form_attributes %}{% endblock %}
        >

            {{ include('@SonataAdmin/Helper/render_form_dismissable_errors.html.twig') }}

            {{ block('sonata_pre_fieldsets') }}
            {{ block('sonata_tab_content') }}
            {{ block('sonata_post_fieldsets') }}
            {{ form_rest(form) }}
            <div class="sonata-ba-form-actions well well-small form-actions">
                <button type="submit" class="btn btn-success" name="btn_create">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                    Crear Receta
                </button>
                <a href="{{ path('admin_app_apppaciente_list') }}" class="btn btn-default" title="Cancelar">
                    <i class="fa fa-backward" aria-hidden="true"></i>
                    Regresar
                </a>
            </div>
        </form>
    {% endif %}

    {{ sonata_block_render_event('sonata.admin.edit.form.bottom', { 'admin': admin, 'object': object }) }}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.box-title')[0].append('para {{ paciente.nombre }}');

            $('#{{ admin.uniqid }}_numero').parent().addClass('col-md-6');
            $('#{{ admin.uniqid }}_fecha_refraccion').parent().parent().parent().addClass('col-md-6');
            $('#{{ admin.uniqid }}_dp').parent().addClass('col-md-6');
            $('#{{ admin.uniqid }}_add').parent().addClass('col-md-6');
            $('#{{ admin.uniqid }}_lista_espejuelo').parent().addClass('col-md-12');
            let input_ojo = {
                "eje_od": {'class': 'col-md-3'},
                "a_visual_od": {'class': 'col-md-3'},
                "cristal_od": {'class': 'col-md-6'},

                "eje_oi": {'class': 'col-md-3'},
                "a_visual_oi": {'class': 'col-md-3'},
                "cristal_oi": {'class': 'col-md-6'}
            };

            for (var k in input_ojo) {
                $('#{{ admin.uniqid }}_' + k).parent().addClass(input_ojo[k].class);

            }


            function checkbox() {
                let limit = 1; //change according to your need
                let checkboxes = $("input:checkbox");//get all the checkbox
                if (checkboxes.filter(":checked").length >= limit) {
                    //if limit is reached disbaled all except checked and #man7
                    //else put an alert here instead of below lines.
                    checkboxes.not(":checked,#man7").iCheck('disable');
                } else {
                    //else enable it all
                    checkboxes.not(":checked").iCheck('enable');
                }

                $.each(checkboxes.filter(':checked'), function (key, item) {
                    if (item.value === 'bifocal' || item.value === 'progresivos') {
                        $('#{{ admin.uniqid }}_add').prop('required', true);
                    }
                });

                checkboxes.on('ifUnchecked', function (event) {
                    if (event.target.value === 'bifocal' || event.target.value === 'progresivos') {
                        $('#{{ admin.uniqid }}_add').prop('required', false);
                    }
                });

                checkboxes.on('ifChecked', function (event) {
                    if (event.target.value === 'bifocal' || event.target.value === 'progresivos') {
                        $('#{{ admin.uniqid }}_add').prop('required', true);
                    }
                })
            }

            $('input[name="{{ admin.uniqid }}[lista_espejuelo][]"]').on("ifChanged", function () {
                checkbox();
            });

            checkbox();

            $('form').on('submit', function () {
                $('form').find('label[class="error"]').remove();
            });

        });
    </script>
{% endblock %}

src/Resources/views/Admin/receta/edit.html.twig
{% extends '@SonataAdmin/CRUD/base_edit.html.twig' %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sonata-ba-field-container-{{ admin.uniqid }}_numero').addClass('col-md-2');
            $('#sonata-ba-field-container-{{ admin.uniqid }}_fecha').addClass('col-md-2');
            $('#sonata-ba-field-container-{{ admin.uniqid }}_dp').addClass('col-md-2');
            $('#sonata-ba-field-container-{{ admin.uniqid }}_add').addClass('col-md-2');
            let input_ojo = ["eje_od", "a_visual_od", "cristal_od","eje_oi", "a_visual_oi", "cristal_oi"];

            for (let i = 0; i < input_ojo.length; i++) {
                $('#sonata-ba-field-container-{{ admin.uniqid }}_'+input_ojo[i]).addClass('col-md-4');
            }

            {#$('#sonata-ba-field-container-{{ admin.uniqid }}_eje_od').addClass('col-md-2');#}
            {#$('#sonata-ba-field-container-{{ admin.uniqid }}_eje_od').addClass('col-md-2');#}
            {#$('#sonata-ba-field-container-{{ admin.uniqid }}_eje_od').addClass('col-md-2');#}

        });
    </script>
{% endblock %}

src/Resources/views/Admin/receta/field__espejuelo.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    {# @var object \App\Entity\AppReceta #}
    <div>
        <table class="table table-striped table-hover" style="margin: 0;padding: 0;">
            <thead>
            <tr>
                <th></th>
                <th>Cristal</th>
                <th>Eje</th>
                <th>Agudeza Visual</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><strong>OD:</strong></td>
                <td>{{ object.cristalOd }}</td>
                <td>{{ object.ejeOd }}</td>
                <td>{{ object.aVisualOd }}</td>
            <tr>
                <td><strong>OI:</strong></td>
                <td>{{ object.cristalOi }}</td>
                <td>{{ object.ejeOi }}</td>
                <td>{{ object.aVisualOi }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

src/Resources/views/Admin/receta/field__espejuelo_tipo.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    {# @var object \App\Entity\AppReceta #}
    <div>
        {{ object.listaEspejuelo|ArrayToList }}
    </div>
{% endblock %}

src/Resources/views/Admin/receta/lista_receta.html.twig
{% extends "SonataAdminBundle:CRUD:base_list.html.twig" %}
{% block tab_menu %}
{% endblock %}
{% block actions %}
{% endblock %}
{% block list_filters %}
    {% if admin.datagrid.filters %}
        {% form_theme form get_admin_template('filter', admin.code) %}

        <div class="col-xs-12 col-md-12 sonata-filters-box"
             style="display: {{ admin.datagrid.hasDisplayableFilters ? 'block' : 'none' }}"
             id="filter-container-{{ admin.uniqid() }}">
            <div class="box box-primary">
                <div class="box-body">
                    <form class="sonata-filter-form form-horizontal {{ admin.isChild and 1 == admin.datagrid.filters|length ? 'hide' : '' }}"
                          action="{#{ admin.generateUrl('lista_receta_paciente', {"id": id}) }#}" method="GET"
                          role="form">
                        {{ form_errors(form) }}

                        <div class="row">
                            <div class="col-sm-9">
                                {% set withAdvancedFilter = false %}
                                {% for filter in admin.datagrid.filters %}
                                    {% set filterActive = ((filter.isActive() and filter.options['show_filter'] is null) or (filter.options['show_filter'] is same as(true))) and not admin.isDefaultFilter(filter.formName) %}
                                    {% set filterVisible = filter.options['show_filter'] is same as(true) or filter.options['show_filter'] is null %}
                                    <div class="form-group {% block sonata_list_filter_group_class %}{% endblock %}"
                                         id="filter-{{ admin.uniqid }}-{{ filter.name }}"
                                         sonata-filter="{{ filterVisible ? 'true' : 'false' }}"
                                         style="display: {% if filterActive %}block{% else %}none{% endif %}">
                                        {% if filter.label is not same as(false) %}
                                            <label for="{{ form[filter.formName].children['value'].vars.id }}"
                                                   class="col-sm-3 control-label">{{ filter.label|trans({}, filter.translationDomain ?: admin.translationDomain) }}</label>
                                        {% endif %}
                                        {% set attr = form[filter.formName].children['type'].vars.attr|default({}) %}

                                        <div class="col-sm-4 advanced-filter">
                                            {{ form_widget(form[filter.formName].children['type'], {'attr':  attr}) }}
                                        </div>

                                        <div class="col-sm-4">
                                            {{ form_widget(form[filter.formName].children['value']) }}
                                        </div>

                                        <div class="col-sm-1">
                                            <label class="control-label">
                                                <a href="#" class="sonata-toggle-filter sonata-ba-action"
                                                   filter-target="filter-{{ admin.uniqid }}-{{ filter.name }}"
                                                   filter-container="filter-container-{{ admin.uniqid() }}">
                                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>
                                                </a>
                                            </label>
                                        </div>
                                    </div>

                                    {% if filter.options['advanced_filter'] %}
                                        {% set withAdvancedFilter = true %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="col-sm-3 text-center">
                                <input type="hidden" name="filter[_page]" id="filter__page" value="1">

                                {% set foo = form['_page'].setRendered() %}
                                {{ form_rest(form) }}

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-filter"
                                           aria-hidden="true"></i> {{ 'btn_filter'|trans({}, 'SonataAdminBundle') }}
                                    </button>

{#                                    <a class="btn btn-default"#}
{#                                       href="{{ admin.generateUrl('lista_receta_paciente', {"id": id, filters: 'reset'}) }}">#}
{#                                        {{ 'link_reset_filter'|trans({}, 'SonataAdminBundle') }}#}
{#                                    </a>#}
                                </div>

                                {% if withAdvancedFilter %}
                                    <div class="form-group">
                                        <a href="#" data-toggle="advanced-filter">
                                            <i class="fa fa-cogs" aria-hidden="true"></i>
                                            {{ 'btn_advanced_filters'|trans({}, 'SonataAdminBundle') }}
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        {% for paramKey, paramValue in admin.persistentParameters %}
                            <input type="hidden" name="{{ paramKey }}" value="{{ paramValue }}">
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block list_footer %}
     {{ parent() }}

{#    <div class="sonata-ba-form-actions well well-small form-actions">#}
{#        <a href="{{ path('admin_app_apppaciente_list') }}" class="btn btn-default" title="Cancelar">#}
{#            <i class="fa fa-backward" aria-hidden="true"></i>#}
{#            Regresar#}
{#        </a>#}
{#    </div>#}
{% endblock %}

src/Resources/views/Admin/receta/lista_receta_paciente.html.twig
{% extends "SonataAdminBundle:CRUD:base_list.html.twig" %}
{% block tab_menu %}
{% endblock %}
{% block actions %}
{% endblock %}
{% block list_filters %}
    {% if admin.datagrid.filters %}
        {% form_theme form get_admin_template('filter', admin.code) %}

        <div class="col-xs-12 col-md-12 sonata-filters-box"
             style="display: {{ admin.datagrid.hasDisplayableFilters ? 'block' : 'none' }}"
             id="filter-container-{{ admin.uniqid() }}">
            <div class="box box-primary">
                <div class="box-body">
                    <form class="sonata-filter-form form-horizontal {{ admin.isChild and 1 == admin.datagrid.filters|length ? 'hide' : '' }}"
                          action="{{ admin.generateUrl('lista_receta_paciente', {"id": id}) }}" method="GET"
                          role="form">
                        {{ form_errors(form) }}

                        <div class="row">
                            <div class="col-sm-9">
                                {% set withAdvancedFilter = false %}
                                {% for filter in admin.datagrid.filters %}
                                    {% set filterActive = ((filter.isActive() and filter.options['show_filter'] is null) or (filter.options['show_filter'] is same as(true))) and not admin.isDefaultFilter(filter.formName) %}
                                    {% set filterVisible = filter.options['show_filter'] is same as(true) or filter.options['show_filter'] is null %}
                                    <div class="form-group {% block sonata_list_filter_group_class %}{% endblock %}"
                                         id="filter-{{ admin.uniqid }}-{{ filter.name }}"
                                         sonata-filter="{{ filterVisible ? 'true' : 'false' }}"
                                         style="display: {% if filterActive %}block{% else %}none{% endif %}">
                                        {% if filter.label is not same as(false) %}
                                            <label for="{{ form[filter.formName].children['value'].vars.id }}"
                                                   class="col-sm-3 control-label">{{ filter.label|trans({}, filter.translationDomain ?: admin.translationDomain) }}</label>
                                        {% endif %}
                                        {% set attr = form[filter.formName].children['type'].vars.attr|default({}) %}

                                        <div class="col-sm-4 advanced-filter">
                                            {{ form_widget(form[filter.formName].children['type'], {'attr':  attr}) }}
                                        </div>

                                        <div class="col-sm-4">
                                            {{ form_widget(form[filter.formName].children['value']) }}
                                        </div>

                                        <div class="col-sm-1">
                                            <label class="control-label">
                                                <a href="#" class="sonata-toggle-filter sonata-ba-action"
                                                   filter-target="filter-{{ admin.uniqid }}-{{ filter.name }}"
                                                   filter-container="filter-container-{{ admin.uniqid() }}">
                                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>
                                                </a>
                                            </label>
                                        </div>
                                    </div>

                                    {% if filter.options['advanced_filter'] %}
                                        {% set withAdvancedFilter = true %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="col-sm-3 text-center">
                                <input type="hidden" name="filter[_page]" id="filter__page" value="1">

                                {% set foo = form['_page'].setRendered() %}
                                {{ form_rest(form) }}

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-filter"
                                           aria-hidden="true"></i> {{ 'btn_filter'|trans({}, 'SonataAdminBundle') }}
                                    </button>

                                    <a class="btn btn-default"
                                       href="{{ admin.generateUrl('lista_receta_paciente', {"id": id, filters: 'reset'}) }}">
                                        {{ 'link_reset_filter'|trans({}, 'SonataAdminBundle') }}
                                    </a>
                                </div>

                                {% if withAdvancedFilter %}
                                    <div class="form-group">
                                        <a href="#" data-toggle="advanced-filter">
                                            <i class="fa fa-cogs" aria-hidden="true"></i>
                                            {{ 'btn_advanced_filters'|trans({}, 'SonataAdminBundle') }}
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        {% for paramKey, paramValue in admin.persistentParameters %}
                            <input type="hidden" name="{{ paramKey }}" value="{{ paramValue }}">
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block list_footer %}
     {{ parent() }}

    <div class="sonata-ba-form-actions well well-small form-actions">
        <a href="{{ path('admin_app_apppaciente_list') }}" class="btn btn-default" title="Cancelar">
            <i class="fa fa-backward" aria-hidden="true"></i>
            Regresar
        </a>
    </div>
{% endblock %}